// Export all constants from a central location
const { AUTH_CONSTANTS, USER_STATUS, AUTH_ERRORS, AUTH_SUCCESS } = require('./auth');
const { ORDER_CONSTANTS, ORDER_STATUS, PAYMENT_STATUS, SHIPPING_STATUS } = require('./orders');
const { PRODUCT_CONSTANTS, PRODUCT_STATUS, PRODUCT_TYPES } = require('./products');
const { NOTIFICATION_CONSTANTS, NOTIFICATION_TYPES, NOTIFICATION_CHANNELS } = require('./notifications');
const { PAYMENT_CONSTANTS, PAYMENT_METHODS, PAYMENT_GATEWAYS } = require('./payments');
const { SYSTEM_CONSTANTS, API_ENDPOINTS, ERROR_CODES } = require('./system');
const { BUSINESS_CONSTANTS, BRANCHES, CURRENCIES } = require('./business');

module.exports = {
  // Auth
  AUTH_CONSTANTS,
  USER_STATUS,
  AUTH_ERRORS,
  AUTH_SUCCESS,
  
  // Orders
  ORDER_CONSTANTS,
  ORDER_STATUS,
  PAYMENT_STATUS,
  SHIPPING_STATUS,
  
  // Products
  PRODUCT_CONSTANTS,
  PRODUCT_STATUS,
  PRODUCT_TYPES,
  
  // Notifications
  NOTIFICATION_CONSTANTS,
  NOTIFICATION_TYPES,
  NOTIFICATION_CHANNELS,
  
  // Payments
  PAYMENT_CONSTANTS,
  PAYMENT_METHODS,
  PAYMENT_GATEWAYS,
  
  // System
  SYSTEM_CONSTANTS,
  API_ENDPOINTS,
  ERROR_CODES,
  
  // Business
  BUSINESS_CONSTANTS,
  BRANCHES,
  CURRENCIES
};